import { McpServer } from '../../server.js';
import { z } from 'zod';
import path from 'path';
import fs from 'fs-extra';
import { MetadataService } from '../../services/MetadataService.js';
import { JSForceService } from '../../services/JSForceService.js';
import { DeploymentService } from '../../services/DeploymentService.js';
import { getMetadataPath, writeFile, deleteFile, exists } from '../../utils/file.js';
import { sfDevNameSchema } from '../../utils/validation.js';

export function registerLwcTools(server: McpServer): void {
  // create_lwc
  server.tool(
    'create_lwc',
    'Create a new Lightning Web Component (LWC)',
    {
      lwcName: sfDevNameSchema.describe('Name of the LWC (camelCase recommended)'),
      html: z.string().optional().describe('HTML file content'),
      js: z.string().optional().describe('JavaScript file content'),
      css: z.string().optional().describe('CSS file content'),
      jsMetaXml: z.string().optional().describe('js-meta.xml configuration content (autogenerated if not provided)'),
      autoDeploy: z.boolean().optional().default(true).describe('Automatically deploy component to default org'),
      targetOrg: z.string().optional().describe('Username or alias of target org'),
    },
    async (params) => {
      try {
        const defaultHtml = `<template>\n    <!-- LWC content here -->\n</template>`;
        const defaultJs = `import { LightningElement } from 'lwc';\n\nexport default class ${params.lwcName.charAt(0).toUpperCase() + params.lwcName.slice(1)} extends LightningElement {\n    \n}`;
        const defaultCss = `/* LWC Styles */`;

        const files = {
          html: params.html || defaultHtml,
          js: params.js || defaultJs,
          css: params.css || defaultCss,
          jsMetaXml: params.jsMetaXml,
        };

        const result = await MetadataService.createLwc(params.lwcName, files, {
          autoDeploy: params.autoDeploy,
          targetOrg: params.targetOrg,
        });

        return {
          content: [
            {
              type: 'text',
              text: `LWC component '${params.lwcName}' created locally.\n` +
                    `Created files:\n${result.filePaths.join('\n')}\n\n` +
                    `Deployment status: ${result.deployResult ? JSON.stringify(result.deployResult, null, 2) : 'Skipped auto-deploy'}`,
            },
          ],
        };
      } catch (error: any) {
        return {
          isError: true,
          content: [{ type: 'text', text: `Failed to create LWC: ${error.message}` }],
        };
      }
    }
  );

  // update_lwc
  server.tool(
    'update_lwc',
    'Update an existing LWC component file (HTML, JS, CSS, XML) and deploy it',
    {
      lwcName: sfDevNameSchema.describe('Name of the LWC component'),
      fileName: z.string().describe('Filename to update (e.g. componentName.js, componentName.html, componentName.css)'),
      content: z.string().describe('Updated content of the file'),
      autoDeploy: z.boolean().optional().default(true).describe('Automatically deploy to default org'),
      targetOrg: z.string().optional().describe('Username or alias of target org'),
    },
    async (params) => {
      try {
        const folderPath = getMetadataPath('lwc', params.lwcName);
        if (!(await exists(folderPath))) {
          throw new Error(`LWC folder '${params.lwcName}' does not exist locally.`);
        }

        const filePath = path.join(folderPath, params.fileName);
        await writeFile(filePath, params.content);

        let deployResult;
        if (params.autoDeploy) {
          deployResult = await DeploymentService.deploy({
            metadata: [`LightningComponentBundle:${params.lwcName}`],
            targetOrg: params.targetOrg,
          });
        }

        return {
          content: [
            {
              type: 'text',
              text: `LWC file '${params.fileName}' updated locally.\n` +
                    `Deployment status: ${deployResult ? JSON.stringify(deployResult, null, 2) : 'Skipped auto-deploy'}`,
            },
          ],
        };
      } catch (error: any) {
        return {
          isError: true,
          content: [{ type: 'text', text: `Failed to update LWC file: ${error.message}` }],
        };
      }
    }
  );

  // delete_lwc
  server.tool(
    'delete_lwc',
    'Delete LWC locally and from the Salesforce org',
    {
      lwcName: sfDevNameSchema.describe('Name of the LWC to delete'),
      autoDeploy: z.boolean().optional().default(true).describe('Automatically delete from org using Tooling API'),
      targetOrg: z.string().optional().describe('Username or alias of target org'),
    },
    async (params) => {
      try {
        const folderPath = getMetadataPath('lwc', params.lwcName);
        if (await exists(folderPath)) {
          await fs.remove(folderPath);
        }

        let deleteStatus = 'Deleted locally.';

        if (params.autoDeploy) {
          try {
            // Find component bundle ID via Tooling API
            // Note: API Name is DeveloperName in LightningComponentBundle
            const queryResult = await JSForceService.query(
              `SELECT Id FROM LightningComponentBundle WHERE DeveloperName = '${params.lwcName}'`,
              true,
              params.targetOrg
            );
            if (queryResult.records && queryResult.records.length > 0) {
              const bundleId = queryResult.records[0].Id;
              const conn = await JSForceService.getConnection(params.targetOrg);
              await conn.tooling.sobject('LightningComponentBundle').destroy(bundleId);
              deleteStatus += ' Deleted from Salesforce org via Tooling API.';
            } else {
              deleteStatus += ' Not found in the Salesforce org, no remote deletion needed.';
            }
          } catch (apiError: any) {
            deleteStatus += ` Remote deletion failed: ${apiError.message}`;
          }
        }

        return {
          content: [{ type: 'text', text: deleteStatus }],
        };
      } catch (error: any) {
        return {
          isError: true,
          content: [{ type: 'text', text: `Failed to delete LWC: ${error.message}` }],
        };
      }
    }
  );

  // generate_apex_controller
  server.tool(
    'generate_apex_controller',
    'Generate an Apex Controller backing class for an LWC and deploy it',
    {
      className: sfDevNameSchema.describe('Name of the Apex controller class'),
      lwcName: sfDevNameSchema.describe('Name of the LWC targeting this controller'),
      methods: z.array(z.string()).describe('List of aura-enabled method names to generate'),
      apiVersion: z.string().optional().describe('API Version (default 60.0)'),
      autoDeploy: z.boolean().optional().default(true).describe('Automatically deploy controller to org'),
      targetOrg: z.string().optional().describe('Username or alias of target org'),
    },
    async (params) => {
      try {
        let code = `public with sharing class ${params.className} {\n\n`;
        for (const method of params.methods) {
          code += `    @AuraEnabled(cacheable=true)\n`;
          code += `    public static String ${method}() {\n`;
          code += `        try {\n`;
          code += `            // TODO: Implement logic\n`;
          code += `            return 'Success';\n`;
          code += `        } catch (Exception e) {\n`;
          code += `            throw new AuraHandledException(e.getMessage());\n`;
          code += `        }\n`;
          code += `    }\n\n`;
        }
        code += `}\n`;

        const result = await MetadataService.createApexClass(params.className, code, {
          apiVersion: params.apiVersion,
          autoDeploy: params.autoDeploy,
          targetOrg: params.targetOrg,
        });

        return {
          content: [
            {
              type: 'text',
              text: `Apex Controller class '${params.className}' created locally for LWC '${params.lwcName}'.\n` +
                    `File paths:\n${result.filePaths.join('\n')}\n\n` +
                    `Deployment status: ${result.deployResult ? JSON.stringify(result.deployResult, null, 2) : 'Skipped auto-deploy'}`,
            },
          ],
        };
      } catch (error: any) {
        return {
          isError: true,
          content: [{ type: 'text', text: `Failed to generate Apex controller: ${error.message}` }],
        };
      }
    }
  );
}
